// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web platformu desteklenmemektedir. Bu uygulama sadece Android için tasarlanmıştır.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS platformu desteklenmemektedir. Bu uygulama sadece Android için tasarlanmıştır.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS platformu desteklenmemektedir. Bu uygulama sadece Android için tasarlanmıştır.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows platformu desteklenmemektedir. Bu uygulama sadece Android için tasarlanmıştır.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux platformu desteklenmemektedir. Bu uygulama sadece Android için tasarlanmıştır.',
        );
      default:
        throw UnsupportedError(
          'Bu platform desteklenmemektedir. Sadece Android cihazlarda çalışır.',
        );
    }
  }

  /// Android Firebase Configuration
  /// Bu ayarlar google-services.json dosyasından alınmıştır
  static const FirebaseOptions android = FirebaseOptions(
    // Android API Key - google-services.json -> client -> api_key -> current_key
    apiKey: 'AIzaSyCOKhT6gipYKAjo43d4nXpxoWrBKDpQZ5w',

    // Android App ID - google-services.json -> client -> client_info -> mobilesdk_app_id
    appId: '1:508468914079:android:a07982a4c71fc7d8d17faa',

    // Messaging Sender ID - google-services.json -> project_info -> project_number
    messagingSenderId: '508468914079',

    // Project ID - google-services.json -> project_info -> project_id
    projectId: 'djmobilapp',

    // Storage Bucket - google-services.json -> project_info -> storage_bucket
    storageBucket: 'djmobilapp.firebasestorage.app',

    // Android Client ID (isteğe bağlı) - OAuth için gerekli değilse boş bırakılabilir
    // androidClientId: 'YOUR_ANDROID_CLIENT_ID',

    // Database URL (Realtime Database kullanıyorsanız)
    // databaseURL: 'https://djmobilapp-default-rtdb.firebaseio.com/',

    // Auth Domain (Authentication kullanıyorsanız)
    // authDomain: 'djmobilapp.firebaseapp.com',
  );
}

/// Firebase Configuration Helper Class
/// Firebase ayarlarını kontrol etmek ve doğrulamak için yardımcı sınıf
class FirebaseConfigHelper {

  /// Firebase konfigürasyonunun geçerli olup olmadığını kontrol eder
  static bool isConfigurationValid() {
    try {
      final config = DefaultFirebaseOptions.android;

      // Temel alanların dolu olup olmadığını kontrol et
      return config.apiKey.isNotEmpty &&
          config.appId.isNotEmpty &&
          config.messagingSenderId.isNotEmpty &&
          config.projectId.isNotEmpty;
    } catch (e) {
      return false;
    }
  }

  /// Platform desteğini kontrol eder
  static bool isPlatformSupported() {
    try {
      DefaultFirebaseOptions.currentPlatform;
      return true;
    } catch (e) {
      return false;
    }
  }

  /// Hata mesajları için yardımcı metod
  static String getConfigurationError() {
    if (!isPlatformSupported()) {
      return 'Bu platform desteklenmemektedir. Lütfen Android cihaz kullanın.';
    }

    if (!isConfigurationValid()) {
      return 'Firebase konfigürasyonu eksik. Lütfen firebase_options.dart dosyasını kontrol edin.';
    }

    return '';
  }
}

/// Firebase konfigürasyon constants
class FirebaseConfig {
  // Bildirim kanalları
  static const String defaultNotificationChannelId = 'djmobilapp_notifications';
  static const String defaultNotificationChannelName = 'DJ Mobil App Bildirimleri';
  static const String defaultNotificationChannelDescription = 'DJ Mobil App genel bildirimleri';

  // Bildirim kategorileri
  static const String musicNotificationChannelId = 'music_notifications';
  static const String musicNotificationChannelName = 'Müzik Bildirimleri';

  static const String promotionNotificationChannelId = 'promotion_notifications';
  static const String promotionNotificationChannelName = 'Promosyon Bildirimleri';

  // FCM Topic'leri (Android için)
  static const String allUsersTopicAndroid = 'all_users_android';
  static const String musicLoversTopicAndroid = 'music_lovers_android';
  static const String premiumUsersTopicAndroid = 'premium_users_android';

  // Firebase özellik bayrakları
  static const bool enableAnalytics = true;
  static const bool enableCrashlytics = true;
  static const bool enablePerformanceMonitoring = true;
  static const bool enableRemoteConfig = true;

  // Android özel ayarları
  static const String androidPackageName = 'com.example.djmobilapp';
  static const int minAndroidSdkVersion = 21; // Android 5.0 (API level 21)
  static const int targetAndroidSdkVersion = 34; // Android 14 (API level 34)
}

/// Firebase Debug Helper
class FirebaseDebugHelper {
  static void printConfiguration() {
    print('🔥 Firebase Configuration Debug Info:');
    print('   Project ID: ${DefaultFirebaseOptions.android.projectId}');
    print('   App ID: ${DefaultFirebaseOptions.android.appId}');
    print('   Sender ID: ${DefaultFirebaseOptions.android.messagingSenderId}');
    print('   API Key: ${DefaultFirebaseOptions.android.apiKey.substring(0, 10)}...');
    print('   Storage Bucket: ${DefaultFirebaseOptions.android.storageBucket}');
    print('   Configuration Valid: ${FirebaseConfigHelper.isConfigurationValid()}');
  }
}